{
  "hash": "2656c9124b697468d5f21ed7c1d14946",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Palmerpenguins Data Analysis\"\nauthor: \"조익현, 정의주, 윤현재, 이유진\"\ndate: \"2025-03-07\"\ncategories: [python, code, analysis]\nimage: \"palmerpenguins.png\"\n---\n\n\n![](palmerpenguins.png){fig-align=\"center\" width=\"50%\"}\n\n## 서론\n\nGitHub에서 제공하는 Palmerpenguins 데이터를 활용하여 남극에 서식하는 펭귄들의 특징을 분석했습니다. 각 종별 신체적 특징과 서식지 분포를 비교하며, 부리 길이, 몸무게 등의 차이를 확인했습니다.\n\n## 주요 분석 결과\n\n-   Adelie: 모든 섬(Biscoe, Dream, Torgersen)에서 발견됨. 부리 길이 짧음, 부리 깊이 보통, 날개 길이 짧음, 몸무게 가벼움 <br>\n-   Chinstrap: Dream 섬에서만 서식함. 부리 길이 가장 김, 부리 깊이 보통, 날개 길이 중간, 몸무게 중간 <br>\n-   Gentoo: Biscoe 섬에서만 서식함. 부리 길이 김, 부리 깊이 가장 얇음, 날개 길이 가장 긺, 몸무게 가장 무거움 <br>\n\n## 데이터 분석 과정\n\n### 1. 데이터 로드\n\n<details style=\"margin-left: 20px;\">\n\n<summary>코드 보기</summary>\n\n::: {#b145c12a .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\n\nfrom palmerpenguins import load_penguins\npenguins = load_penguins()\n```\n:::\n\n\n</details>\n\n### 2. 데이터 전처리\n\n데이터셋에서 일부 NaN 값이 존재하는 것을 확인했습니다.\n\n::: {#59add791 .cell execution_count=2}\n``` {.python .cell-code}\npenguins.isna().sum()\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```\nspecies               0\nisland                0\nbill_length_mm        2\nbill_depth_mm         2\nflipper_length_mm     2\nbody_mass_g           2\nsex                  11\nyear                  0\ndtype: int64\n```\n:::\n:::\n\n\n분석의 정확성을 높이기 위해 NaN 값을 **수치형 변수는 0**으로 **범주형 변수는 X로 대체**했습니다.\n\n<details style=\"margin-left: 20px;\">\n\n<summary>코드 보기</summary>\n\n::: {#885850b9 .cell execution_count=3}\n``` {.python .cell-code}\npenguins.loc[penguins[\"bill_length_mm\"].isna(), \"bill_length_mm\"] = 0\npenguins.loc[penguins[\"bill_depth_mm\"].isna(), \"bill_depth_mm\"] = 0\npenguins.loc[penguins[\"flipper_length_mm\"].isna(), \"flipper_length_mm\"] = 0\npenguins.loc[penguins[\"body_mass_g\"].isna(), \"body_mass_g\"] = 0\npenguins.loc[penguins[\"sex\"].isna(), \"sex\"] = \"X\"\n\npenguins.isna().sum()\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\nspecies              0\nisland               0\nbill_length_mm       0\nbill_depth_mm        0\nflipper_length_mm    0\nbody_mass_g          0\nsex                  0\nyear                 0\ndtype: int64\n```\n:::\n:::\n\n\n</details>\n\n::: {#fce5fd9e .cell execution_count=4}\n``` {.python .cell-code}\npenguins.isna().sum()\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```\nspecies              0\nisland               0\nbill_length_mm       0\nbill_depth_mm        0\nflipper_length_mm    0\nbody_mass_g          0\nsex                  0\nyear                 0\ndtype: int64\n```\n:::\n:::\n\n\n### 3. 데이터 분석\n\n#### 1. 각 종별 펭귄수 구하기\n\n<details style=\"margin-left: 20px;\">\n\n<summary>코드 보기</summary>\n\n::: {#5104e363 .cell execution_count=5}\n``` {.python .cell-code}\nspecies_counts = {}\n\nfor species in penguins[\"species\"].unique(): \n    species_counts[species] = penguins.loc[penguins[\"species\"] == species, \"species\"].shape[0]\n```\n:::\n\n\n</details>\n\n결과 값\n\n| Species   | Count |\n|-----------|-------|\n| Adelie    | 152   |\n| Gentoo    | 124   |\n| Chinstrap | 68    |\n\n##### 요약\n\n펭귄 개체 수는 Adelie(152) \\> Gentoo(124) \\> Chinstrap(68) 순으로 분포하고 있음을 확인할 수 있습니다.\n\n#### 2. 서식지별 펭귄 분포 및 특징 분석\n\n2-1 서식지별 펭귄 개체 수 비교\n\n<details style=\"margin-left: 20px;\">\n\n<summary>코드 보기</summary>\n\n::: {#c2084fe2 .cell execution_count=6}\n``` {.python .cell-code}\nisland_list = [\"Biscoe\", \"Dream\", \"Torgersen\"]\nisland_counts = {}\n\nfor island in island_list:\n    island_counts[island] = penguins.loc[penguins[\"island\"] == island, \"island\"].shape[0]\n```\n:::\n\n\n</details>\n\n결과 값\n\n| Island    | count |\n|-----------|-------|\n| Biscoe    | 168   |\n| Dream     | 124   |\n| Torgersen | 52    |\n\n2-2. 서식지별 종별 개체 수 분석\n\n<details style=\"margin-left: 20px;\">\n\n<summary>코드 보기</summary>\n\n::: {#18438a92 .cell execution_count=7}\n``` {.python .cell-code}\nisland_species_counts = {}\n\n\nfor island in penguins[\"island\"].unique():  \n    island_species_counts[island] = {}\n    \n    # 각 종별 반복\n    for species in penguins[\"species\"].unique():  \n        count = penguins.loc[(penguins[\"island\"] == island) & (penguins[\"species\"] == species), \"species\"].shape[0]\n        island_species_counts[island][species] = count\n\nisland_species_counts\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```\n{'Torgersen': {'Adelie': 52, 'Gentoo': 0, 'Chinstrap': 0},\n 'Biscoe': {'Adelie': 44, 'Gentoo': 124, 'Chinstrap': 0},\n 'Dream': {'Adelie': 56, 'Gentoo': 0, 'Chinstrap': 68}}\n```\n:::\n:::\n\n\n</details>\n\n결과 값\n\n| Island    | Adelie | Chinstrap | Gentoo |\n|-----------|--------|-----------|--------|\n| Biscoe    | 44     | 0         | 124    |\n| Dream     | 56     | 68        | 0      |\n| Torgersen | 52     | 0         | 0      |\n\n##### 요약\n\nAdelie는 남극의 다양한 환경에서도 살아갈 수 있는 종이며,  \nChinstrap과 Gentoo는 특정 섬에서만 발견되어 서식지가 제한적인 경향을 보였습니다.  \nBiscoe 섬이 가장 많은 펭귄이 서식하는 주요 서식지라는 점도 확인되었습니다.\n\n\n#### 3. 펭귄 부리 특징 분석\n\n3-1. 펭귄 부리 특성\n\n<details style=\"margin-left: 20px;\">\n\n<summary>코드 보기</summary>\n\n::: {#c1168adb .cell execution_count=8}\n``` {.python .cell-code}\nbill_length_max = penguins[\"bill_length_mm\"].max()\nbill_length_min = penguins.loc[penguins[\"bill_length_mm\"] > 0, \"bill_length_mm\"].min()\nbill_length_mean = penguins[\"bill_length_mm\"].mean() \n```\n:::\n\n\n</details>\n\n결과 값\n\n| Metric           | Value(mm) |\n|------------------|-----------|\n| Max Bill Length  | 59.6      |\n| Min Bill Length  | 32.1      |\n| Mean Bill Length | 43.6      |\n\n3-2. 종별 부리 특성\n\n<details style=\"margin-left: 20px;\">\n\n<summary>코드 보기</summary>\n\n::: {#c20f6000 .cell execution_count=9}\n``` {.python .cell-code}\nspecies_bill_length = {}\n\nfor species in penguins[\"species\"].unique(): \n    species_bill_length[species] = {\n        \"max\": penguins.loc[penguins[\"species\"] == species, \"bill_length_mm\"].max(),\n        \"min\": penguins.loc[(penguins[\"species\"] == species) & (penguins[\"bill_length_mm\"] > 0), \"bill_length_mm\"].min(),\n        \"mean\": penguins.loc[penguins[\"species\"] == species, \"bill_length_mm\"].mean()\n    }\n\nspecies_bill_length\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```\n{'Adelie': {'max': 46.0, 'min': 32.1, 'mean': np.float64(38.536184210526315)},\n 'Gentoo': {'max': 59.6, 'min': 40.9, 'mean': np.float64(47.12177419354838)},\n 'Chinstrap': {'max': 58.0,\n  'min': 40.9,\n  'mean': np.float64(48.83382352941177)}}\n```\n:::\n:::\n\n\n</details>\n\n결과 값\n\n| Species   | Max Bill Length | Min Bill Length | Mean Bill Length |\n|-----------|-----------------|-----------------|------------------|\n| Adelie    | 46.0            | 32.1            | 38.54            |\n| Gentoo    | 59.6            | 40.9            | 47.12            |\n| Chinstrap | 58.0            | 40.9            | 48.83            |\n\n##### 요약\n\n분석 결과, 펭귄의 부리 길이는 최소 32.1mm에서 최대 59.6mm까지 분포하며, 평균값은 43.6mm로 확인되었습니다. 종별 비교를 통해 Chinstrap \\> Gentoo \\> Adelie 순으로 부리가 긴 것을 확인했습니다.\n\nChinstrap 종이 평균값 기준 가장 긴 부리를 가진 종이며, Gentoo 종은 최대 부리 길이를 가진 개체가 존재하며, 평균값도 높은 편입니다. Adelie 종은 전체적으로 부리가 짧은 편이며, 최소값을 기록한 종입니다.\n\n#### 4. 펭귄 몸무게 특징\n\n4-1 펭귄 몸무게 특징징\n\n<details style=\"margin-left: 20px;\">\n\n<summary>코드 보기</summary>\n\n::: {#59445232 .cell execution_count=10}\n``` {.python .cell-code}\nbody_mass_max = penguins[\"body_mass_g\"].max()\nbody_mass_min = penguins.loc[penguins[\"body_mass_g\"] > 0, \"body_mass_g\"].min()\nbody_mass_mean = penguins[\"body_mass_g\"].mean()\n```\n:::\n\n\n</details>\n\n결과 값\n\n| Metric         | Value(g) |\n|----------------|----------|\n| Max Body Mass  | 6300.0   |\n| Min Body Mass  | 2700.0   |\n| Mean Body Mass | 4177.33  |\n\n4-2. 종별 몸무게 특징\n\n<details style=\"margin-left: 20px;\">\n\n<summary>코드 보기</summary>\n\n::: {#8359694f .cell execution_count=11}\n``` {.python .cell-code}\nspecies_bill_length = {}\n\nspecies_body_mass = {}\n\nfor species in penguins[\"species\"].unique():  # 각 종별 반복\n    species_body_mass[species] = {\n        \"max\": penguins.loc[penguins[\"species\"] == species, \"body_mass_g\"].max(),\n        \"min\": penguins.loc[(penguins[\"species\"] == species) & (penguins[\"body_mass_g\"] > 0), \"body_mass_g\"].min(),\n        \"mean\": penguins.loc[penguins[\"species\"] == species, \"body_mass_g\"].mean()\n    }\n```\n:::\n\n\n</details>\n\n결과 값\n\n| Species   | Max Body Mass(g) | Min Body Mass(g) | Mean Body Mass(g) |\n|-----------|------------------|------------------|-------------------|\n| Adelie    | 4775.0           | 2850.0           | 3676.32           |\n| Gentoo    | 6300.0           | 3950.0           | 5035.08           |\n| Chinstrap | 4800.0           | 2700.0           | 3733.09           |\n\n\\##### 요약\n\n펭귄의 몸무게는 최소 2700g에서 최대 6300g까지 분포하며, 평균적으로 4177.33인 것을 알 수 있습니다.\n\n종별로 비교했을 때, Gentoo \\> Chinstrap \\> Adelie 순으로 몸무게가 무거운 것을 확인 할 수 있었습니다.\n\n결론적으로, Gentoo 종은 평균적으로 가장 무거운 펭귄이며, 최대 몸무게를 기록한 개체도 포함하고 있습니다. Adelie 종은 가장 가벼운 종으로, 체중 범위도 가장 낮은 쪽에 분포합니다. Chinstrap 종은 Adelie보다 약간 무겁지만, Gentoo에 비하면 몸무게가 가벼운 편입니다.\n\n### 4. 결론\n\n이번 분석을 통해 남극에 서식하는 펭귄들의 개체 수, 부리 길이, 몸무게 차이 및 서식지 분포를 비교하였습니다.\n\n-   **개체 수 및 서식지 분포**\n\n펭귄 개체 수는 Adelie(152) \\> Gentoo(124) \\> Chinstrap(68) 순으로 많음을 확인하였습니다.\n\nAdelie 종은 가장 많은 개체 수를 보이며, Biscoe, Dream, Torgersen 섬 등 다양한 환경에서 서식하는 특징을 보였습니다. Gentoo 종은 Biscoe 섬에서만 발견되었으며, 특정 서식지에서만 서식하는 경향을 보였습니다. Chinstrap 종은 Dream 섬에서만 서식하며, 서식 환경이 제한적인 특성을 나타내었습니다. Biscoe 섬이 전체적으로 가장 많은 펭귄이 서식하는 주요 서식지라는 점도 확인되었습니다.\n\n-   **부리 길이 비교**\n\n펭귄의 부리 길이는 최소 32.1mm \\~ 최대 59.6mm 범위로 분포하며, 평균값은 43.6mm로 확인되었습니다. 종별로 비교했을 때 Chinstrap \\> Gentoo \\> Adelie 순으로 부리가 긴 경향을 보였습니다.\n\nChinstrap 종이 평균적으로 가장 긴 부리를 가지며, 평균 48.8mm로 확인되었습니다. Gentoo 종은 개체별 차이가 크며, 최대 59.6mm로 가장 긴 개체가 존재하였습니다. Adelie 종은 전체적으로 부리가 짧은 편이며, 최소값(32.1mm)을 기록한 종이었습니다. 이러한 차이는 종별 먹이 섭취 방식과 환경 적응력과 관련될 가능성이 있으며, 추가적인 연구가 필요해 보입니다.\n\n-   **몸무게 비교**\n\n펭귄의 몸무게는 최소 2700g \\~ 최대 6300g 사이에서 분포하며, 평균값은 4177.33g으로 확인되었습니다. 종별 비교 결과, Gentoo \\> Chinstrap \\> Adelie 순으로 무거운 경향을 보였습니다.\n\nGentoo 종은 평균 5035.08g으로 가장 무거운 종이며, 최대 6300g의 개체가 포함되어 있습니다. Chinstrap 종은 평균 3733.09g으로, Adelie보다 약간 무거운 특성을 보였습니다. Adelie 종은 평균 3676.32g으로 가장 가벼운 종이며, 최소 2850g의 개체도 포함되어 있었습니다.\n\n#### 종합 결론\n\n분석 결과, Adelie는 다양한 환경에서 서식하는 종이며, Gentoo와 Chinstrap은 특정 섬에서만 발견되는 경향을 보이는 종임을 확인하였습니다. 부리 길이와 몸무게에서도 종별로 유의미한 차이가 있으며, 이는 먹이 섭취 방식, 환경 적응력, 서식지 특성과 밀접한 관련이 있을 가능성이 높습니다. 추후 연구에서는 기후 변화, 서식지 조건, 개체군 이동 패턴 등과의 관계를 추가적으로 분석할 필요가 있습니다.\n\n-   참고\n\n    각 종별 개체 수(Adelie 152마리, Gentoo 124마리, Chinstrap 68마리)가 다르지만, 이번 분석에서는 개체 수 차이에 따른 가중치를 적용하지 않고 단순 평균값을 기준으로 비교하였습니다. 이는 종별 평균적인 특징 차이를 직관적으로 파악하기 위한 목적이며, 개체 수에 따른 세부적인 영향은 추가적인 분석을 통해 고려할 수 있을 것입니다.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}