project:
  type: website
  output-dir: docs

website:
  title: "우당탕탕 빅데이터 분석 도전기"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



